import { z } from "zod";

import { USER_ROLES } from "./enums";

/**
 * Normalises Kenyan mobile numbers to E.164 (+2547XXXXXXXX / +2541XXXXXXXX).
 * Accepts "0712 345 678", "712345678", "254712345678" and "+254712345678".
 * Returns null when the input is not a valid Kenyan mobile number.
 */
export function normalizeKenyanPhone(input: string): string | null {
  const digits = input.replace(/[\s\-()]/g, "").replace(/^\+/, "");
  const local = digits.startsWith("254")
    ? digits.slice(3)
    : digits.startsWith("0")
      ? digits.slice(1)
      : digits;
  return /^[17]\d{8}$/.test(local) ? `+254${local}` : null;
}

export const phoneSchema = z
  .string()
  .trim()
  .transform((value, ctx) => {
    const phone = normalizeKenyanPhone(value);
    if (!phone) {
      ctx.addIssue({ code: "custom", message: "Enter a valid Kenyan phone number" });
      return z.NEVER;
    }
    return phone;
  });

export const PIN_MIN_LENGTH = 4;
export const PIN_MAX_LENGTH = 6;

export const pinSchema = z
  .string()
  .regex(
    new RegExp(`^\\d{${PIN_MIN_LENGTH},${PIN_MAX_LENGTH}}$`),
    `PIN must be ${PIN_MIN_LENGTH}–${PIN_MAX_LENGTH} digits`,
  );

export const mobileLoginRequestSchema = z.object({
  phone: phoneSchema,
  pin: pinSchema,
  /** Stable per-install UUID generated by the phone. */
  deviceId: z.uuid(),
  /** Human-readable device name, e.g. "Samsung A14". */
  deviceLabel: z.string().trim().min(1).max(64),
});
export type MobileLoginRequest = z.input<typeof mobileLoginRequestSchema>;

export const authUserSchema = z.object({
  id: z.string(),
  name: z.string().nullable(),
  phone: z.string().nullable(),
  role: z.enum(USER_ROLES),
});
export type AuthUser = z.infer<typeof authUserSchema>;

export const mobileDeviceSchema = z.object({
  id: z.uuid(),
  label: z.string(),
  receiptPrefix: z.string(),
});
export type MobileDevice = z.infer<typeof mobileDeviceSchema>;

export const mobileLoginResponseSchema = z.object({
  token: z.string(),
  /** ISO timestamp. */
  expiresAt: z.iso.datetime(),
  user: authUserSchema,
  device: mobileDeviceSchema,
});
export type MobileLoginResponse = z.infer<typeof mobileLoginResponseSchema>;

export const meResponseSchema = z.object({
  user: authUserSchema,
  device: mobileDeviceSchema.nullable(),
});
export type MeResponse = z.infer<typeof meResponseSchema>;

/** Error body returned by every API route. `code` is stable; `message` is for humans. */
export const apiErrorSchema = z.object({
  error: z.object({
    code: z.enum([
      "BAD_REQUEST",
      "UNAUTHORIZED",
      "FORBIDDEN",
      "NOT_FOUND",
      "INVALID_CREDENTIALS",
      "ACCOUNT_LOCKED",
      "ACCOUNT_DISABLED",
      "DEVICE_DISABLED",
      "INTERNAL",
    ]),
    message: z.string(),
  }),
});
export type ApiError = z.infer<typeof apiErrorSchema>;
export type ApiErrorCode = ApiError["error"]["code"];
